--Purpose: Script to create all schema objects

--The results of running this script will be spooled
--into 'spoolCreate.txt'

--\o 'spoolCreate.txt'

-- Output script execution data
\qecho -n 'Script run on '
\qecho -n `date /t`
\qecho -n 'at '
\qecho `time /t`
\qecho -n 'Script run by ' :USER ' on server ' :HOST ' with db ' :DBNAME
\qecho ' '
\qecho 


BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS USERS(
	ID SERIAL NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR NOT NULL CHECK(LENGTH(TRIM(FIRSTNAME)) > 0),
    LASTNAME VARCHAR NOT NULL CHECK(LENGTH(TRIM(LASTNAME)) > 0),
    HASHEDPASSWORD CHAR(20) NOT NULL,
    PROFPIC BOOLEAN,
    PRIVACYSETTING JSON,
    NOTIFICATIONSETTING JSON
);

CREATE TABLE IF NOT EXISTS USERNAME(
    ID SERIAL NOT NULL REFERENCES USERS,
    USERNAME VARCHAR NOT NULL UNIQUE,
    PRIMARY KEY (ID, USERNAME)
);

CREATE TABLE IF NOT EXISTS USEREMAIL(
    ID SERIAL NOT NULL REFERENCES USERS,
    EMAIL VARCHAR NOT NULL UNIQUE CHECK(TRIM(EMAIL) LIKE '_%@_%._%'),
    PRIMARY KEY (ID, EMAIL)
);

CREATE TABLE IF NOT EXISTS TRUSTEDDEVICE(
    ID SERIAL NOT NULL REFERENCES USERS,
    AUTHTOKEN VARCHAR NOT NULL,
    PRIMARY KEY (ID, AUTHTOKEN)
);

CREATE TABLE IF NOT EXISTS CURRENTSESSION(
    ID SERIAL NOT NULL REFERENCES USERS,
    SESSIONID VARCHAR NOT NULL,
    PRIMARY KEY (ID, SESSIONID)
);

CREATE TABLE IF NOT EXISTS POST(
    ID SERIAL NOT NULL PRIMARY KEY,
    POSTERID SERIAL NOT NULL REFERENCES USERS,
    PARENTPOSTID SERIAL REFERENCES POST,
    MEDIA BYTEA,
    TEXTCONTENT VARCHAR NOT NULL,
    POSTTIME TIMESTAMP NOT NULL,
    POSTLOC POINT
);

CREATE TABLE IF NOT EXISTS REPLY(
    ID SERIAL NOT NULL PRIMARY KEY,
    SENDERID SERIAL NOT NULL REFERENCES USERS,
    PARENTPOSTID SERIAL NOT NULL REFERENCES POST,
    PARENTREPLYID SERIAL REFERENCES REPLY,
    TEXTCONTENT VARCHAR NOT NULL,
    REPLYTIME TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS FOLLOW(
    FOLLOWER SERIAL NOT NULL REFERENCES USERS,
    FOLLOWEDUSER SERIAL NOT NULL REFERENCES USERS,
    PRIMARY KEY(FOLLOWER, FOLLOWEDUSER)
);

CREATE TABLE IF NOT EXISTS BLOCK(
    BLOCKER SERIAL NOT NULL REFERENCES USERS,
    BLOCKEDUSER SERIAL NOT NULL REFERENCES USERS,
    PRIMARY KEY (BLOCKER, BLOCKEDUSER)
);

COMMIT

\qecho ' '
\qecho ---------------------------------------------------------------------
\qecho End of script

-- Turn off spooling
--\o