--Purpose: Script to create all schema objects

--The results of running this script will be spooled
--into 'spoolCreate.txt'

--\o 'spoolCreate.txt'

-- Output script execution data
\qecho -n 'Script run on '
\qecho -n `date /t`
\qecho -n 'at '
\qecho `time /t`
\qecho -n 'Script run by ' :USER ' on server ' :HOST ' with db ' :DBNAME
\qecho ' '
\qecho 


BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS User(
    USERNAME VARCHAR NOT NULL CHECK TRIM(USERNAME)<>'' PRIMARY KEY,
    EMAIL VARCHAR NOT NULL UNIQUE CHECK TRIM(EMAIL LIKE '_%@_%._%'),
    HASHEDPASSWORD VARCHAR NOT NULL,
    PROFPIC BYTEA,
    PRIVACYSETTING VARCHAR,
    NOTIFICATIONSETTING VARCHAR
);

CREATE TABLE IF NOT EXISTS TRUSTEDDEVICE(
    USERID SERIAL NOT NULL REFERENCES USER,
    AUTHTOKEN VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CURRENTSESSION(
    USERID SERIAL NOT NULL REFERENCES USER,
    SESSIONID VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS POST(
    ID SERIAL NOT NULL PRIMARY KEY,
    POSTERID SERIAL NOT NULL REFERENCES USER,
    ORIGINID SERIAL REFERENCES POST,
    MEDIA BYTEA,
    TEXTCONTENT VARCHAR NOT NULL,
    POSTTIME TIMESTAMP NOT NULL,
    LOCATION POINT
);

CREATE TABLE IF NOT EXISTS REPLY(
    ID SERIAL NOT NULL PRIMARY KEY,
    SENDERID SERIAL NOT NULL REFERENCES USER,
    ORIGINID SERIAL NOT NULL REFERENCES POST,
    REPLYID SERIAL REFERENCES REPLY,
    TEXTCONTENT VARCHAR NOT NULL,
    REPLYTIME TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS FOLLOW(
    FOLLOWER SERIAL REFERENCES USER,
    FOLLOWEDUSER SERIAL REFERENCES USER
);

CREATE TABLE IF NOT EXISTS BLOCK(
    BLOCKER SERIAL REFERENCES USER,
    BLOCKEDUSER SERIAL REFERENCES USER
);

COMMIT

\qecho ' '
\qecho ---------------------------------------------------------------------
\qecho End of script

-- Turn off spooling
--\o